export const WORDS = [
  "STONE","PLATE","SMILE","TRAIN","CLOUD","BREAD","WATER","MUSIC","LIGHT","BRICK",
  "APPLE","RIVER","HOUSE","MONEY","GHOST","SNAKE","WORLD","POWER","NURSE","SHEEP",
  "HONEY","SOUND","GREEN","BLACK","WHITE","PIZZA","CHAIR","PHONE","SHIRT","STACK",
  "SWEET","SALTY","SPICY","CRISP","FROST","FLAME","SPARK","NIGHT","DREAM","SHINE"
];
